"use client";

import { useState } from "react";

export default function InfoModal() {
  const [isOpen, setIsOpen] = useState(false);
  const [lang, setLang] = useState<"pl" | "en">("pl");
  const [expandedGuidelines, setExpandedGuidelines] = useState(false);

  const content = {
    pl: {
      title: "O Projekcie FLASHBET PRO",
      subtitle: "Eksperyment: Człowiek vs AI",
      sections: [
        {
          heading: "🎯 Cel Projektu",
          text: "Ten projekt został stworzony, aby sprawdzić, czy sztuczna inteligencja jest w stanie pokonać człowieka w przewidywaniu wyników meczów piłkarskich.",
        },
        {
          heading: "🤖 Technologia",
          text: "Predykcje są generowane przez Google Gemini Pro (Flash 2.0), model AI najnowszej generacji, który analizuje statystyki, formę drużyn i historyczne wyniki.",
        },
        {
          heading: "📊 Zasady Predykcji",
          text: "AI działa na podstawie jasnych wytycznych:\n• Analiza ostatnich 5-10 meczów obu drużyn\n• Uwzględnienie meczów u siebie/na wyjeździe\n• Ocena średniej bramek, posiadania piłki i Expected Goals (xG)\n• Selekcja tylko zdarzeń o prawdopodobieństwie >85%\n• Wszystkie typy są zapisywane PRZED rozpoczęciem meczu",
        },
        {
          heading: "⚖️ Sprawiedliwa Rywalizacja",
          text: "Kupony są rozliczane automatycznie po zakończeniu meczu na podstawie oficjalnych wyników z Flashscore API. Nie ma możliwości manipulacji danymi.",
        },
      ],
      guidelines: {
        title: "🧠 Wytyczne Systemowe AI (ASA-100)",
        role: "Rola: Algorytmiczny Analityk Sportowy",
        description:
          "AI działa jako bezemocionalna maszyna analityczna, której jedynym celem jest maksymalizacja trafności predykcji (hit rate). Nie jest kibicem – jest kalkulatorem prawdopodobieństwa.",
        principles: [
          {
            icon: "🎲",
            title: "Próg Pewności: >85%",
            desc: "Jeśli w zbiorze meczów nie ma zdarzenia o prawdopodobieństwie >85%, system zwraca 'BRAK TYPÓW' zamiast typować na siłę.",
          },
          {
            icon: "🚫",
            title: "Zero Emocji",
            desc: "Ignorowane są: kursy bukmacherskie, 'przeczucia', historia klubu, magia pucharu. Liczą się TYLKO twarde dane statystyczne.",
          },
          {
            icon: "📈",
            title: "Algorytm 3-Stopniowy",
            desc: "1) Filtr wstępny (odrzucenie towarzyskich i lig egzotycznych)\n2) Analiza głęboka (forma, H2H, kadra, motywacja)\n3) Weryfikacja ryzyka (czy faworyt może przegrać?)",
          },
          {
            icon: "⚙️",
            title: "Kluczowe Metryki",
            desc: "• Forma: ostatnie 5-10 spotkań\n• Bilans Home/Away\n• Expected Goals (xG)\n• Kontuzje kluczowych zawodników\n• Kontekst (o co grają?)",
          },
          {
            icon: "🎯",
            title: "Jakość > Ilość",
            desc: "Lepiej 1 typ o skuteczności 95% niż 10 typów o skuteczności 60%. System może zwrócić pojedynczy typ lub wcale żadnego.",
          },
        ],
      },
      footer:
        "Projekt ma charakter edukacyjny i eksperymentalny. Nie stanowi zachęty do hazardu.",
    },
    en: {
      title: "About FLASHBET PRO Project",
      subtitle: "Experiment: Human vs AI",
      sections: [
        {
          heading: "🎯 Project Goal",
          text: "This project was created to test whether artificial intelligence can beat humans at predicting football match outcomes.",
        },
        {
          heading: "🤖 Technology",
          text: "Predictions are generated by Google Gemini Pro (Flash 2.0), a next-generation AI model that analyzes statistics, team form, and historical results.",
        },
        {
          heading: "📊 Prediction Guidelines",
          text: "AI operates based on clear rules:\n• Analysis of last 5-10 matches for both teams\n• Home/away match consideration\n• Evaluation of average goals, possession, and Expected Goals (xG)\n• Selection only of events with >85% probability\n• All bets are recorded BEFORE match starts",
        },
        {
          heading: "⚖️ Fair Competition",
          text: "Coupons are automatically settled after match completion using official Flashscore API results. No data manipulation possible.",
        },
      ],
      guidelines: {
        title: "🧠 AI System Guidelines (ASA-100)",
        role: "Role: Algorithmic Sports Analyst",
        description:
          "AI operates as an emotionless analytical machine with a single goal: maximizing prediction hit rate. It's not a fan – it's a probability calculator.",
        principles: [
          {
            icon: "🎲",
            title: "Certainty Threshold: >85%",
            desc: "If no event in the match set has >85% probability, the system returns 'NO TIPS' instead of forcing predictions.",
          },
          {
            icon: "🚫",
            title: "Zero Emotions",
            desc: "Ignored: betting odds, 'gut feelings', club history, cup magic. Only HARD statistical data matters.",
          },
          {
            icon: "📈",
            title: "3-Step Algorithm",
            desc: "1) Initial filter (reject friendlies and exotic leagues)\n2) Deep analysis (form, H2H, squad, motivation)\n3) Risk verification (can the favorite lose?)",
          },
          {
            icon: "⚙️",
            title: "Key Metrics",
            desc: "• Form: last 5-10 matches\n• Home/Away balance\n• Expected Goals (xG)\n• Key player injuries\n• Context (what's at stake?)",
          },
          {
            icon: "🎯",
            title: "Quality > Quantity",
            desc: "Better 1 tip with 95% accuracy than 10 tips with 60%. System may return a single tip or none at all.",
          },
        ],
      },
      footer:
        "This is an educational and experimental project. Not an encouragement for gambling.",
    },
  };

  const current = content[lang];

  return (
    <>
      {/* Button Trigger */}
      <button
        onClick={() => setIsOpen(true)}
        className="fixed bottom-6 right-6 w-14 h-14 bg-yellow-500 hover:bg-yellow-600 text-black rounded-full shadow-2xl flex items-center justify-center text-2xl font-black transition-all z-40 hover:scale-110 active:scale-95"
        aria-label="Informacje o projekcie"
      >
        ?
      </button>

      {/* Modal */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/90 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-in fade-in"
          onClick={() => setIsOpen(false)}
        >
          <div
            className="bg-[#242424] w-full max-w-2xl rounded-2xl border-2 border-yellow-500/30 shadow-2xl max-h-[90vh] overflow-y-auto custom-scrollbar"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-yellow-500/20 to-yellow-600/10 p-6 border-b border-gray-800 sticky top-0 z-10 backdrop-blur-md">
              <div className="flex justify-between items-start mb-2">
                <div className="flex-1">
                  <h2 className="text-2xl font-black text-white uppercase tracking-tight">
                    {current.title}
                  </h2>
                  <p className="text-yellow-500 text-sm font-bold mt-1">
                    {current.subtitle}
                  </p>
                </div>
                <button
                  onClick={() => setIsOpen(false)}
                  className="text-gray-400 hover:text-white text-3xl leading-none transition-colors ml-4"
                >
                  ×
                </button>
              </div>

              {/* Language Switcher */}
              <div className="flex gap-2 mt-4">
                <button
                  onClick={() => setLang("pl")}
                  className={`px-4 py-1.5 rounded-lg text-xs font-bold uppercase transition-all ${
                    lang === "pl"
                      ? "bg-yellow-500 text-black"
                      : "bg-[#333] text-gray-400 hover:bg-[#444]"
                  }`}
                >
                  🇵🇱 Polski
                </button>
                <button
                  onClick={() => setLang("en")}
                  className={`px-4 py-1.5 rounded-lg text-xs font-bold uppercase transition-all ${
                    lang === "en"
                      ? "bg-yellow-500 text-black"
                      : "bg-[#333] text-gray-400 hover:bg-[#444]"
                  }`}
                >
                  🇬🇧 English
                </button>
              </div>
            </div>

            {/* Content */}
            <div className="p-6 space-y-6">
              {current.sections.map((section, idx) => (
                <div
                  key={idx}
                  className="bg-[#2a2a2a] p-5 rounded-lg border border-gray-800"
                >
                  <h3 className="text-sm font-black text-yellow-500 uppercase mb-3 tracking-wide">
                    {section.heading}
                  </h3>
                  <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-line">
                    {section.text}
                  </p>
                </div>
              ))}

              {/* ACCORDION: AI Guidelines */}
              <div className="bg-[#2a2a2a] rounded-lg border-2 border-yellow-500/30 overflow-hidden">
                <button
                  onClick={() => setExpandedGuidelines(!expandedGuidelines)}
                  className="w-full p-5 flex items-center justify-between hover:bg-[#333] transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">
                      {expandedGuidelines ? "📖" : "📕"}
                    </span>
                    <div className="text-left">
                      <h3 className="text-sm font-black text-yellow-500 uppercase tracking-wide">
                        {current.guidelines.title}
                      </h3>
                      <p className="text-xs text-gray-500 mt-0.5">
                        {current.guidelines.role}
                      </p>
                    </div>
                  </div>
                  <svg
                    className={`w-5 h-5 text-yellow-500 transition-transform ${
                      expandedGuidelines ? "rotate-180" : ""
                    }`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M19 9l-7 7-7-7"
                    />
                  </svg>
                </button>

                {expandedGuidelines && (
                  <div className="p-5 pt-0 space-y-4 animate-in slide-in-from-top-2">
                    <p className="text-gray-400 text-xs italic leading-relaxed border-l-2 border-yellow-500/50 pl-3">
                      {current.guidelines.description}
                    </p>

                    <div className="space-y-3">
                      {current.guidelines.principles.map((principle, idx) => (
                        <div
                          key={idx}
                          className="bg-[#1a1a1a] p-4 rounded-lg border border-gray-800 hover:border-yellow-500/30 transition-colors"
                        >
                          <div className="flex items-start gap-3">
                            <span className="text-2xl flex-shrink-0">
                              {principle.icon}
                            </span>
                            <div>
                              <h4 className="text-xs font-bold text-white mb-1.5">
                                {principle.title}
                              </h4>
                              <p className="text-xs text-gray-400 leading-relaxed whitespace-pre-line">
                                {principle.desc}
                              </p>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>

                    <div className="bg-yellow-500/10 border border-yellow-500/30 p-4 rounded-lg">
                      <p className="text-xs text-yellow-500 font-bold flex items-center gap-2">
                        <span>⚡</span>
                        <span>
                          {lang === "pl"
                            ? "Algorytm może odmówić typowania, jeśli nie znajdzie 'pewniaka' – to cecha, nie błąd."
                            : "The algorithm may refuse to predict if it doesn't find a 'sure thing' – this is a feature, not a bug."}
                        </span>
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Footer */}
            <div className="p-6 border-t border-gray-800 bg-[#1a1a1a]">
              <p className="text-xs text-gray-500 italic text-center">
                {current.footer}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Custom Scrollbar Styles */}
      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #1a1a1a;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #444;
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #555;
        }
      `}</style>
    </>
  );
}
